from __future__ import annotations

from dataclasses import dataclass

import torch
from torch import nn


def _check_2d(name: str, values: torch.Tensor, dimension: int | None = None) -> None:
    if values.ndim != 2:
        raise ValueError(f"{name} must be a 2D tensor")
    if dimension is not None and values.shape[1] != dimension:
        raise ValueError(
            f"{name} has latent width {values.shape[1]}, expected {dimension}"
        )
    if not bool(torch.isfinite(values).all()):
        raise ValueError(f"{name} contains non-finite values")


class BoundedBilinearInteraction(nn.Module):
    """Identity-preserving correction to a factorized reaction-enzyme pairing.

    Base FIBRE scoring is the dual pairing R @ E.T between normalized
    reaction-demand and enzyme-capability coordinates. This module learns only
    a small cross-coordinate interaction R @ (I + B) @ E.T.

    B starts exactly at zero. It is rescaled in the forward pass so its
    Frobenius norm is at most max_frobenius_norm; therefore its operator norm is
    bounded by the same constant and, for unit-norm embeddings, the absolute
    score perturbation is bounded by that constant.

    The construction never changes the input domain. Any reaction/enzyme that
    the base encoders can represent remains scoreable.
    """

    def __init__(self, dimension: int, max_frobenius_norm: float = 0.10) -> None:
        super().__init__()
        if dimension <= 0:
            raise ValueError("dimension must be positive")
        if not 0.0 < float(max_frobenius_norm) <= 1.0:
            raise ValueError("max_frobenius_norm must be in (0, 1]")
        self.dimension = int(dimension)
        self.max_frobenius_norm = float(max_frobenius_norm)
        self.delta = nn.Parameter(torch.zeros(self.dimension, self.dimension))

    def bounded_delta(self) -> torch.Tensor:
        raw_norm = torch.linalg.vector_norm(self.delta)
        scale = torch.clamp(
            torch.as_tensor(
                self.max_frobenius_norm,
                dtype=self.delta.dtype,
                device=self.delta.device,
            )
            / raw_norm.clamp_min(torch.finfo(self.delta.dtype).eps),
            max=1.0,
        )
        return self.delta * scale

    def score_matrix(
        self,
        reaction_embeddings: torch.Tensor,
        enzyme_embeddings: torch.Tensor,
    ) -> torch.Tensor:
        _check_2d("reaction_embeddings", reaction_embeddings, self.dimension)
        _check_2d("enzyme_embeddings", enzyme_embeddings, self.dimension)
        base = reaction_embeddings @ enzyme_embeddings.T
        delta = self.bounded_delta()
        return base + (reaction_embeddings @ delta) @ enzyme_embeddings.T

    def score_pairs(
        self,
        reaction_embeddings: torch.Tensor,
        enzyme_embeddings: torch.Tensor,
    ) -> torch.Tensor:
        _check_2d("reaction_embeddings", reaction_embeddings, self.dimension)
        _check_2d("enzyme_embeddings", enzyme_embeddings, self.dimension)
        if reaction_embeddings.shape != enzyme_embeddings.shape:
            raise ValueError("paired reaction/enzyme embeddings must have equal shape")
        base = (reaction_embeddings * enzyme_embeddings).sum(dim=1)
        correction = (
            (reaction_embeddings @ self.bounded_delta()) * enzyme_embeddings
        ).sum(dim=1)
        return base + correction

    def diagnostics(self) -> dict[str, float]:
        with torch.no_grad():
            raw = float(torch.linalg.vector_norm(self.delta).cpu())
            bounded = float(torch.linalg.vector_norm(self.bounded_delta()).cpu())
        return {
            "raw_frobenius_norm": raw,
            "bounded_frobenius_norm": bounded,
            "operator_norm_upper_bound": bounded,
            "max_frobenius_norm": self.max_frobenius_norm,
        }


@dataclass(frozen=True)
class PositivePairConditioner:
    """Train-free low-rank update generated by accepted enzyme-reaction pairs.

    With unit embeddings r_i, e_i and non-negative evidence weights alpha_i, the
    update is Delta = sum_i alpha_i r_i e_i^T. At query time this adds a
    separable product-kernel correction around the accepted pairs.

    The update is rescaled as one matrix to a declared Frobenius-norm budget, so
    new wet-lab observations can refine ranking without changing encoder
    coverage or requiring gradient training.
    """

    delta: torch.Tensor
    raw_frobenius_norm: float
    bounded_frobenius_norm: float
    pair_count: int
    max_frobenius_norm: float

    @classmethod
    def from_positive_pairs(
        cls,
        reaction_embeddings: torch.Tensor,
        enzyme_embeddings: torch.Tensor,
        *,
        weights: torch.Tensor | None = None,
        max_frobenius_norm: float = 0.10,
    ) -> "PositivePairConditioner":
        if reaction_embeddings.ndim != 2 or enzyme_embeddings.ndim != 2:
            raise ValueError("positive-pair embeddings must be 2D")
        if reaction_embeddings.shape != enzyme_embeddings.shape:
            raise ValueError("positive reaction/enzyme embeddings must align")
        if not len(reaction_embeddings):
            raise ValueError("at least one positive pair is required")
        if not 0.0 < float(max_frobenius_norm) <= 1.0:
            raise ValueError("max_frobenius_norm must be in (0, 1]")
        if weights is None:
            local_weights = torch.ones(
                len(reaction_embeddings),
                dtype=reaction_embeddings.dtype,
                device=reaction_embeddings.device,
            )
        else:
            local_weights = weights.reshape(-1).to(
                dtype=reaction_embeddings.dtype,
                device=reaction_embeddings.device,
            )
            if len(local_weights) != len(reaction_embeddings):
                raise ValueError("weights must align to positive pairs")
            if bool((local_weights < 0).any()) or not bool(
                torch.isfinite(local_weights).all()
            ):
                raise ValueError("weights must be finite and non-negative")
        raw = torch.einsum(
            "n,ni,nj->ij",
            local_weights,
            reaction_embeddings,
            enzyme_embeddings,
        )
        raw_norm_tensor = torch.linalg.vector_norm(raw)
        cap = torch.as_tensor(
            float(max_frobenius_norm), dtype=raw.dtype, device=raw.device
        )
        scale = torch.clamp(
            cap / raw_norm_tensor.clamp_min(torch.finfo(raw.dtype).eps), max=1.0
        )
        delta = (raw * scale).detach()
        return cls(
            delta=delta,
            raw_frobenius_norm=float(raw_norm_tensor.detach().cpu()),
            bounded_frobenius_norm=float(
                torch.linalg.vector_norm(delta).detach().cpu()
            ),
            pair_count=int(len(reaction_embeddings)),
            max_frobenius_norm=float(max_frobenius_norm),
        )


def conditioned_pair_scores(
    reaction_embeddings: torch.Tensor,
    enzyme_embeddings: torch.Tensor,
    conditioner: PositivePairConditioner,
) -> torch.Tensor:
    if reaction_embeddings.ndim != 2 or enzyme_embeddings.ndim != 2:
        raise ValueError("paired query embeddings must be 2D")
    if reaction_embeddings.shape != enzyme_embeddings.shape:
        raise ValueError("paired query embeddings must align")
    if reaction_embeddings.shape[1] != conditioner.delta.shape[0]:
        raise ValueError("conditioner latent dimension mismatch")
    base = (reaction_embeddings * enzyme_embeddings).sum(dim=1)
    correction = ((reaction_embeddings @ conditioner.delta) * enzyme_embeddings).sum(
        dim=1
    )
    return base + correction
