from __future__ import annotations


def n(id, parent, label, status, family, why, result, legacy, kind='experiment', main=False):
    return dict(id=id,parent=parent,label=label,status=status,family=family,why=why,result=result,legacy=legacy,kind=kind,main=main)


NODES = [
    n('enzymecage', None, 'EnzymeCAGE', 'root', 'root',
      'Start from the structure-aware enzyme–reaction ranking system we were trying to improve.',
      'It worked inside a bounded support/candidate regime but exposed coverage, scoreability and open-world limits.',
      'Root of the whole Engineering lineage.', kind='milestone', main=True),
    n('pocket_audit', 'enzymecage', 'Pocket robustness audit', 'turn', 'structure',
      'First verify that downstream ranking failure is not simply caused by choosing the wrong predicted pocket.',
      'On a 50-reaction slice, first-pocket and official-pocket Top-5/Top-10 were both 54%/68%; multi-pocket aggregation did not improve them, while 52.46% of pairs had their highest structure score outside pocket 1.',
      'Established that richer local pocket evidence exists, but naive aggregation is not the missing ranking principle.', kind='experiment', main=True),
    n('full_library_structure', 'pocket_audit', 'Full-library structural pair screen', 'turn', 'structure',
      'Test whether near-complete EnzymeCAGE structural scoring can directly prioritize enzymes across a real library.',
      'For 10 TPS reactions against 1,391 proteins, 13,790 structural pair scores still yielded zero Top-1/5/10 hits, MRR about 0.0037 and median best-positive rank 387.',
      'Separated pairwise compatibility scoring from large-candidate retrieval.', kind='milestone', main=True),
    n('reaction_transfer', 'full_library_structure', 'Reaction-similarity transfer', 'turn', 'candidate',
      'Use chemically similar known reactions to create a much smaller candidate reservoir before structural ranking.',
      'The 10-query screen improved MRR to about 0.0622 and median best-positive rank to 16.5, proving that candidate-space structure matters.',
      'Created the first successful retrieval gate, and exposed its eventual recall ceiling.', kind='experiment', main=True),
    n('closed_pool', 'reaction_transfer', 'Closed candidate-pool system', 'turn', 'root',
      'Organize the original practical workflow around candidate generation, CAGE scoring and rescue.',
      'Strong for in-database completion; every downstream step depended on the positive entering the pool.',
      'Made candidate coverage the first major problem definition.', kind='milestone', main=True),
    n('recall_union', 'closed_pool', 'High-recall candidate union', 'turn', 'candidate',
      'Build a high-recall reservoir before expensive scoring.', 'Efficient, but excluded positives became unrecoverable.',
      'Forced open candidate-space thinking.'),
    n('cage_pool_rank', 'closed_pool', 'CAGE pool-internal structural ranking', 'local', 'structure',
      'Use structural/pocket evidence to distinguish candidates in the reservoir.',
      'Important early signal; limited by support coverage and raw-score behavior.',
      'Returned later as family-specific structural expertise.'),
    n('conditional_cage_rescue', 'cage_pool_rank', 'Conditional CAGE rescue', 'local', 'structure',
      'Use structural evidence only for candidates that can be scored reliably.', 'Useful as a bounded rescue rather than a universal score.', 'Early availability-aware structure pattern.'),
    n('cage_prob_fusion', 'cage_pool_rank', 'Direct raw CAGE probability fusion', 'reject', 'structure',
      'Use CAGE probabilities directly as a fine-grained ranking score.',
      'Sigmoid saturation and ties manufactured unstable fine order.', 'Rejected; structure had to be handled more cautiously.'),
    n('rf_hgb', 'closed_pool', 'Tree-based score fusion', 'reject', 'fusion',
      'Fuse reaction similarity, CAGE and handcrafted features.', 'Useful on the old fixed-pool task, brittle outside it.',
      'Did not become the broad core.'),
    n('rescue_slots', 'closed_pool', 'Main ranking + rescue slots', 'turn', 'fusion',
      'Reserve scarce Top-K positions for strong evidence missed by the main ranker.', 'Practical and interpretable.',
      'Early ancestor of anchored / bounded correction.'),
    n('gate_coverage_ceiling', 'closed_pool', 'Candidate-gate recall ceiling', 'turn', 'candidate',
      'Measure the full-reaction-set cost of relying on a relation-propagated candidate pool.',
      'Only 720 of 1,640 known enzyme records entered the pool: about 43.98% relation coverage. Any missed positive became unrecoverable downstream.',
      'Turned open-world coverage from an implementation detail into the next scientific problem.', kind='milestone', main=True),
    n('open_problem', 'gate_coverage_ceiling', 'Open-world retrieval problem', 'turn', 'root',
      'Require arbitrary new reactions and proteins to enter scoring from their molecular inputs rather than relation-table membership.',
      'The task changed from candidate filtering to bidirectional open retrieval.',
      'Spawned candidate-universe, representation, specialization, uncertainty and workflow branches.', kind='milestone', main=True),

    # Candidate-space program
    n('candidate_program', 'open_problem', 'Candidate space & open-world registry', 'keep', 'candidate',
      'Make new proteins/reactions enter the system without retraining and control what may compete in Top-K.',
      'Established explicit candidate-universe semantics.', 'Feeds Broad and remains a BRIDGE boundary.', kind='program'),
    n('registry', 'candidate_program', 'Persistent + temporary open-world registry', 'keep', 'candidate',
      'Register new entities without rebuilding the entire model.', 'Worked for persistent and request-local entities.',
      'Retained as open-world infrastructure.'),
    n('marts_candidates', 'candidate_program', 'MARTS external reaction/enzyme expansion', 'keep', 'candidate',
      'Broaden beyond the original TPS data.', 'Expanded external coverage and forced stricter evaluation.',
      'Retained in training/evaluation lineage.'),
    n('fewshot', 'candidate_program', 'Seeded few-shot expansion', 'keep', 'candidate',
      'Exploit known positives when the experimental context provides them.', 'Very strong under homolog-visible conditions.',
      'Retained as an explicit contextual capability.'),
    n('fewshot_homolog', 'fewshot', 'Same/near-homolog seed expansion', 'keep', 'candidate',
      'Use local sequence neighborhoods around known positives.', 'High Top-K retrieval when close homologs are allowed.',
      'Kept as a distinct task, not mixed with zero-shot.'),
    n('fewshot_crosscluster', 'fewshot', 'Cross-cluster seed expansion', 'local', 'candidate',
      'Test whether few-shot gains survive when near homologs are excluded.', 'Much harder but scientifically distinct.',
      'Reported separately from homolog-visible few-shot.'),
    n('uniprot', 'candidate_program', 'UniProt TPS expansion', 'turn', 'candidate',
      'Increase the protein universe beyond canonical TPS candidates.', 'Exposed direct competition between coverage and Top-K quality.',
      'Led to controlled expansion rather than free merge.'),
    n('uniprot_free', 'uniprot', 'Free merge of 5,672 extra proteins', 'reject', 'candidate',
      'Maximize discovery coverage.', 'Many unlabeled proteins displaced known positives in scarce Top-K.',
      'Rejected.'),
    n('uniprot_quota', 'uniprot', 'Canonical prefix + controlled tail quota', 'local', 'candidate',
      'Preserve the trusted head while allowing novel candidates to appear.', 'Stable risk-controlled expansion.',
      'Retained as bounded rescue.'),
    n('pfam', 'candidate_program', 'Pfam architecture constraints', 'turn', 'candidate',
      'Use known TPS domain architecture as biological scope evidence.', 'Fine-grained architecture helped; coarse domain logic overgeneralized.',
      'Kept only as scoped evidence.'),
    n('pfam_soft', 'pfam', 'Pfam soft reranking', 'reject', 'candidate',
      'Use domain architecture as a general ranking feature.', 'Development gains were not stable.', 'Rejected.'),
    n('pfam_exact', 'pfam', 'Exact Pfam architecture', 'local', 'candidate',
      'Require complete architecture matches rather than single domains.', 'Small stable local gain.', 'Retained for rescue/audit.'),
    n('pfam_hier', 'pfam', 'Hierarchical single-domain + full architecture', 'reject', 'candidate',
      'Recover candidates with partial architecture evidence.', 'Shared domains mixed unrelated function on frozen evaluation.', 'Rejected.'),
    n('taxonomy', 'candidate_program', 'R2E taxonomy scope', 'keep', 'candidate',
      'Support explicit eukaryote/prokaryote search constraints.', 'Pre-score candidate restriction preserved model semantics.',
      'Retained as a candidate-universe constraint.'),
    n('semantic_scope', 'candidate_program', 'Semantic candidate-universe routing', 'local', 'candidate',
      'Let the interface infer when a query requests TPS-specific vs general scope.', 'Useful application routing.',
      'Kept as orchestration, not model evidence.'),
    n('wetlab_program', 'candidate_program', 'Retrieval-to-wet-lab decision branch', 'keep', 'evaluation',
      'Translate ranked retrieval into a finite experimental campaign instead of treating Top-K as the final artifact.',
      'Candidate source, exploitation, uncertainty and diversity became explicit experimental roles.',
      'Connected model ranking to DBTL execution.', kind='program'),
    n('discovery_panel', 'wetlab_program', 'Discovery panel construction', 'keep', 'evaluation',
      'Build reaction-specific candidate sets with explicit canonical and rescue roles.',
      'Produced auditable per-reaction candidate panels rather than blindly taking the first K scores.',
      'Retained as the wet-lab selection layer.'),
    n('milp_balance', 'discovery_panel', 'MILP inter-plate balancing', 'keep', 'evaluation',
      'Balance reaction class, TPS class, substrate, controls, candidate source, evidence layer, sequence length and Pfam architecture across plates.',
      'The solver reached optimal plate assignments and sharply reduced between-plate covariate ranges.',
      'Retained as experimental-design infrastructure.'),
    n('hungarian_layout', 'milp_balance', 'Hungarian well-position randomization', 'keep', 'evaluation',
      'Prevent candidate role and biological category from confounding physical well position.',
      'Balanced within-block well placement after plate assignment.',
      'Retained as the final physical-layout step.'),
    n('wetlab_feedback', 'hungarian_layout', 'Wet-lab feedback contract', 'keep', 'evaluation',
      'Define how expression-qualified positives, reliable negatives and provenance return to later model iterations.',
      'Separated usable experimental feedback from ambiguous assay failures.',
      'Closes the model-to-experiment engineering loop.'),

    # Broad representation/training program
    n('representation_program', 'open_problem', 'Broad representation & retrieval learning', 'keep', 'representation',
      'Replace IDs and fixed candidate rules with representations that can score arbitrary entities.',
      'Produced the first robust open retrieval core.', 'Primary parent of Broad Retrieval.', kind='program', main=True),
    n('esm_c', 'representation_program', 'ESM-C protein representation', 'keep', 'representation',
      'Encode arbitrary protein sequences.', 'Provided open protein-side features.', 'Retained.'),
    n('drfp', 'representation_program', 'DRFP + reaction categories', 'keep', 'representation',
      'Represent chemical transformations rather than reaction IDs.', 'Supported unseen reaction identities.', 'Retained.'),
    n('dual_tower', 'representation_program', 'Multi-positive bidirectional dual tower', 'keep', 'representation',
      'Learn many-to-many enzyme–reaction compatibility in a scalable retrieval form.', 'Became the durable broad retrieval backbone.',
      'Direct ancestor of Broad Retrieval.', main=True),
    n('pu_mask', 'dual_tower', 'Cluster-aware false-negative protection', 'keep', 'training',
      'Avoid treating unlabelled near-homolog pairs as certain negatives.', 'Reduced destructive negative pressure.', 'Retained.'),
    n('hard_negatives', 'dual_tower', 'Hard-negative training', 'local', 'training',
      'Make training care about realistic head confounders.', 'Useful in moderation; aggressive specialisation became unstable.', 'Partially retained.'),
    n('hard_model', 'hard_negatives', 'Dedicated hard-negative model', 'reject', 'training',
      'Replace the main model with a head-confounder specialist.', 'No stable frozen superiority.', 'Rejected.'),
    n('hard_curriculum', 'hard_negatives', 'Hard-negative curriculum', 'reject', 'training',
      'Increase negative difficulty over training.', 'Failed to become a stable production recipe.', 'Rejected.'),
    n('topk_surrogate', 'dual_tower', 'Budget-focused ranking loss', 'reject', 'training',
      'Optimize the wet-lab budget boundary directly.', 'Sensitive to K and false negatives.', 'Rejected from the main objective.'),
    n('marts_adapt', 'representation_program', 'MARTS domain adaptation', 'keep', 'training',
      'Adapt broad representations to the external terpene domain without losing open retrieval.', 'Improved domain coverage.', 'Retained in production ancestry.'),
    n('frozen_tower', 'marts_adapt', 'Direction-specific tower adaptation', 'local', 'training',
      'Allow R2E and E2R to adapt differently.', 'Useful because the two directions are not symmetric.', 'Foreshadowed direction-specific expert permissions.'),
    n('seed_ensemble', 'marts_adapt', 'Three-seed ensemble', 'keep', 'uncertainty',
      'Reduce optimizer randomness and expose ranking stability.', 'Improved robustness diagnostics.', 'Retained.'),
    n('horizyn', 'representation_program', 'Horizyn transfer family', 'turn', 'representation',
      'Test whether a larger pretrained enzyme–reaction space can replace or strengthen the local representation.',
      'Direct transfer mostly failed; residual use was safer.', 'Established “strong base + incremental external evidence”.'),
    n('horizyn_mlnce', 'horizyn', 'Direct Horizyn contrastive transfer', 'reject', 'representation',
      'Transfer the pretrained joint space directly.', 'Negative cleanroom result.', 'Rejected.'),
    n('horizyn_frozen_rxn', 'horizyn', 'Frozen Horizyn reaction encoder', 'reject', 'representation',
      'Freeze pretrained reaction geometry and adapt protein-side representation.', 'Insufficient ranking quality.', 'Rejected.'),
    n('prott5_bridge', 'horizyn', 'ESM-C → ProtT5 bridge', 'reject', 'representation',
      'Align protein representation spaces expected by different models.', 'Did not solve retrieval performance.', 'Rejected.'),
    n('horizyn_concat', 'horizyn', 'DRFP + Horizyn concatenation', 'reject', 'representation',
      'Fuse local chemical features and external reaction features directly.', 'Unstable feature-scale interaction.', 'Rejected.'),
    n('horizyn_residual', 'horizyn', 'Bounded Horizyn residual transfer', 'local', 'representation',
      'Import only incremental information without replacing the base representation.', 'Useful in restricted budgets and reproducible as a distiller.',
      'Residual principle survived.'),
    n('broad', 'dual_tower', 'Broad Retrieval', 'keep', 'milestone',
      'Make candidate generation itself an ordered full-space retrieval system.',
      'Provided stable open-world ranking and a fallback that does not require optional experts.',
      'Became the universal base order for BRIDGE.', kind='milestone', main=True),
    n('user_semantic_routing', 'broad', 'User-driven semantic scope switching', 'keep', 'context',
      'Real users changed task scope, organism constraints, seeds and retrieval direction conversationally rather than following module boundaries.',
      'Semantic intent switching and context continuation were added before the formal agent.',
      'Established the user-workflow branch from model capability to research interface.', kind='program'),
    n('bounded_agent', 'user_semantic_routing', 'Bounded scientific agent', 'keep', 'context',
      'Let a model plan tool use while keeping entity identity, candidate scope and model execution under deterministic controls.',
      'Created the first end-to-end scientific agent harness with verified recovery paths.',
      'Direct ancestor of the current conversational research system.'),
    n('research_workspace', 'bounded_agent', 'Persistent research workspace', 'keep', 'context',
      'Preserve proteins, reactions, evidence, routes and multi-turn state so one retrieval can become the input to the next task.',
      'Made scientific objects reusable across conversations and downstream analyses.',
      'Turned the agent from a single-turn wrapper into a persistent research workspace.'),
    n('starase_navigator', 'research_workspace', 'Starase Navigator', 'historical', 'context',
      'Unify agent context, evidence cards, pathway ambiguity resolution and reusable workspace objects.',
      'Became the mature pre-COMPASS application identity.',
      'Historical product ancestor of COMPASS.'),
    n('compass', 'starase_navigator', 'COMPASS', 'keep', 'context',
      'Expose the retrieval and evidence system through a conversational orchestration layer aligned with real research workflows.',
      'Current user-facing scientific agent identity.',
      'Receives BRIDGE as the current retrieval method while remaining a distinct product/workflow branch.', kind='milestone'),

    # TPS-specific mechanism program
    n('tps_mech_program', 'open_problem', 'TPS mechanistic specialization', 'turn', 'mechanism',
      'Test whether explicit TPS biochemistry can outperform broad representation learning.',
      'Many biologically appealing features improved local slices but failed broad frozen confirmation.',
      'Eventually returned as a gated TPS specialist.', kind='program'),
    n('motif', 'tps_mech_program', 'Catalytic motif context', 'reject', 'mechanism',
      'Use DDxxD, NSE/DTE, DxDD and related local sequence context.', 'Local discrimination improved; global retrieval remained weak.', 'Rejected as a core ranker.'),
    n('motif_rrf', 'motif', 'Rank-fused motif evidence', 'reject', 'mechanism',
      'Use motif evidence only as a rank-level auxiliary.', 'Development gain did not freeze.', 'Rejected.'),
    n('motif_residual', 'motif', 'Motif residual reranker', 'reject', 'mechanism',
      'Restrict motif evidence to correcting Top-100 mistakes.', 'Frozen optimum returned to zero correction.', 'Rejected.'),
    n('p2rank', 'tps_mech_program', 'Pocket-local representation', 'reject', 'mechanism',
      'Use pocket-local sequence as a closer proxy for substrate selectivity.', 'Some development gain; frozen confirmation failed.', 'Rejected.'),
    n('precursor_neg', 'tps_mech_program', 'Mechanism-matched hard negatives', 'reject', 'mechanism',
      'Construct realistic TPS confounders sharing precursor chemistry.', 'Semantically good but no stable frozen gain.', 'Rejected.'),
    n('mechanism_aux', 'tps_mech_program', 'Mechanism-aware auxiliary supervision', 'reject', 'mechanism',
      'Force representations to encode precursor, topology and oxidation.', 'Labels were too coarse/sparse.', 'Rejected.'),
    n('scaffold_family', 'tps_mech_program', 'Explicit scaffold supervision', 'turn', 'mechanism',
      'Try progressively finer chemical supervision of TPS product structure.', 'Occasional development wins did not survive freezing.', 'Informed later mechanism-evidence caution.'),
    n('coarse_scaffold', 'scaffold_family', 'Coarse scaffold classes', 'reject', 'mechanism',
      'Supervise broad skeleton identity.', 'Unstable.', 'Rejected.'),
    n('morgan_cluster', 'scaffold_family', 'Morgan reaction clusters', 'reject', 'mechanism',
      'Use finer chemistry clusters.', 'Unstable.', 'Rejected.'),
    n('carbon_graph', 'scaffold_family', 'Carbon-connectivity graph', 'reject', 'mechanism',
      'Focus on the carbon rearrangement that TPS enzymes create.', 'No stable frozen improvement.', 'Rejected.'),
    n('carbon_residual', 'carbon_graph', 'Carbon-graph residual', 'reject', 'mechanism',
      'Use carbon topology only as a local correction.', 'Frozen scale returned to zero.', 'Rejected.'),
    n('tps_foundation', 'tps_mech_program', 'TPS foundation R2E model', 'turn', 'mechanism',
      'Rebuild a stronger TPS-specific neural successor after the broad system existed.', 'Provided a domain-specialist ancestry.', 'Fed the later TPS expert, not the universal core.'),
    n('tps_xattn', 'tps_foundation', 'Active-site cross-attention', 'reject', 'mechanism',
      'Model direct interaction between reaction features and active-site tokens.', 'Development winner was invalidated by evaluation alignment; corrected route did not become mainline.', 'Rejected as universal route.'),
    n('enzymarc', 'tps_foundation', 'Support-aware EnzymARC gate', 'local', 'mechanism',
      'Test another open-world TPS-capable model with explicit support constraints.', 'Useful as a support-aware external gate, too expensive / limited for universal scoring.', 'Retained as comparative/support evidence.'),

    # Evidence/reliability program
    n('evidence_program', 'open_problem', 'Evidence, applicability & uncertainty', 'keep', 'uncertainty',
      'Separate model ranking from confidence, evidence provenance and applicability.', 'Created diagnostics that stayed orthogonal to ranking.', 'Several concepts later helped expert gating.', kind='program'),
    n('reliability', 'evidence_program', 'Grouped reliability calibration', 'keep', 'uncertainty',
      'Estimate whether a query is likely to yield a useful top result without calling score a probability.', 'Produced protocol-bound reliability tiers.', 'Retained as a risk layer.'),
    n('abstention', 'reliability', 'Selective abstention', 'keep', 'uncertainty',
      'Avoid overconfident answers far outside the model support.', 'Useful application behavior.', 'Retained outside core ranking.'),
    n('passport', 'evidence_program', 'Candidate Evidence Passport', 'local', 'uncertainty',
      'Bundle route, support and diagnostic evidence without changing score/rank.', 'Made decisions auditable.', 'Retained as provenance/interpretation.'),
    n('applicability_proxy', 'evidence_program', 'Open-world applicability proxy', 'turn', 'uncertainty',
      'Estimate whether a query is represented and ranking-stable.', 'Separated applicability from activity probability.', 'Conceptually anticipated expert applicability.'),
    n('conformal', 'evidence_program', 'Conformal Retrieval Sets', 'local', 'uncertainty',
      'Return a candidate prefix with target marginal coverage rather than a fixed Top-K only.', 'All global calibration combinations passed finite-sample tolerance; sets were often large.', 'Retained as a diagnostic/coverage contract.'),
    n('mondrian', 'conformal', 'Applicability-aware Mondrian conformal', 'local', 'uncertainty',
      'Use different set sizes for strong/moderate/weak applicability groups.', 'Enabled only where calibration/test support was sufficient.', 'Retained with fallback to global calibration.'),
    n('cycle', 'evidence_program', 'Bidirectional cycle consistency', 'local', 'uncertainty',
      'Check whether forward candidates recover the original query in reverse retrieval.', 'Useful explanation signal.', 'Kept as evidence, not ranking authority.'),
    n('cycle_grid', 'cycle', 'Cycle rerank weight grid', 'reject', 'uncertainty',
      'Test whether cycle evidence should directly rerank.', 'Confirmation produced no added hits or MRR gain.', 'Rejected from production ranking.'),

    # Graph/nonparametric program
    n('graph_program', 'open_problem', 'Graph & non-parametric alternatives', 'turn', 'graph',
      'Use neighborhood structure and known associations without relying only on neural similarity.', 'Some restricted routes worked, global graph methods were unstable.', 'Contributed local auxiliary methods.', kind='program'),
    n('graph_diffusion', 'graph_program', 'Graph diffusion', 'reject', 'graph',
      'Propagate known function through the enzyme–reaction graph.', 'Hub amplification and weak double-cold entry.', 'Rejected.'),
    n('multihop', 'graph_program', 'Multi-hop propagation', 'reject', 'graph',
      'Reach farther through indirect graph evidence.', 'Amplified noise and hub effects.', 'Rejected.'),
    n('hub_norm', 'graph_program', 'Candidate hub normalization', 'reject', 'graph',
      'Suppress universally high-scoring hub candidates.', 'Multiple normalizers failed to produce stable gains.', 'Rejected.'),
    n('dual_kernel', 'graph_program', 'Protein + reaction dual kernel', 'turn', 'graph',
      'Require support from both reaction and protein neighborhoods.', 'Current-only version failed freezing; budget-limited MARTS E2R succeeded.', 'Kept only under narrow conditions.'),
    n('dual_kernel_current', 'dual_kernel', 'Current-only dual kernel', 'reject', 'graph',
      'Apply dual-neighborhood propagation to the current dataset.', 'Development gain did not freeze.', 'Rejected.'),
    n('dual_kernel_marts', 'dual_kernel', 'MARTS dual-kernel rescue', 'local', 'graph',
      'Restrict the same idea to a task/budget where neighborhoods were informative.', 'Passed repeated confirmation.', 'Retained as a local route.'),

    # Broad-era generalization program
    n('budget_routing', 'broad', 'Budget-aware retrieval routing', 'keep', 'routing',
      'Different wet-lab budgets reward different trade-offs.', 'Separate production routes outperformed one universal route.', 'Retained as budget-aware routing.'),
    n('generalization_program', 'broad', 'Broad generalization & anti-forgetting', 'turn', 'generalization',
      'Absorb much broader enzyme–reaction evidence without erasing capabilities that already worked.', 'Parameter-space consolidation alone did not solve conditional expertise.', 'Pushed the system toward expert routing.', kind='program'),
    n('continuation_scouting', 'generalization_program', 'Continuation method scouting', 'considered', 'generalization',
      'Survey retention methods before committing expensive retraining.', 'Separated low-cost candidates from high-cost advanced backups.', 'Recorded as design-space evidence.', kind='considered'),
    n('l2sp_considered', 'continuation_scouting', 'L2-SP', 'considered', 'generalization',
      'Regularize parameters toward the source solution.', 'Documented as a retention baseline; not promoted into the frozen mainline.', 'Considered route.', kind='considered'),
    n('der_considered', 'continuation_scouting', 'DER', 'considered', 'generalization',
      'Use replay/distillation to preserve old capability.', 'Studied as a mechanism reference; not promoted into the frozen mainline.', 'Considered route.', kind='considered'),
    n('fdr_considered', 'continuation_scouting', 'FDR', 'considered', 'generalization',
      'Preserve intermediate representations during continuation.', 'Studied as a retention reference; not promoted into the frozen mainline.', 'Considered route.', kind='considered'),
    n('model_soups_considered', 'continuation_scouting', 'Model Soups', 'considered', 'generalization',
      'Consolidate checkpoints after training without another learned merger.', 'Considered alongside WiSE-FT; no independent frozen production branch.', 'Considered route.', kind='considered'),
    n('regmeanpp_considered', 'continuation_scouting', 'RegMean++', 'considered', 'generalization',
      'Explore representation-aware closed-form consolidation beyond RegMean.', 'Documented as a candidate, not promoted into the frozen production line.', 'Considered route.', kind='considered'),
    n('directional_cont', 'generalization_program', 'Full-evidence directional continuation', 'turn', 'generalization',
      'Continue training different towers/directions with broad evidence.', 'Expanded coverage but created explicit retention trade-offs.', 'Established the retention problem.'),
    n('replay_anchor', 'directional_cont', 'Historical replay anchor', 'local', 'generalization',
      'Protect source-domain representations during continuation.', 'Useful retention control.', 'Technique retained locally.'),
    n('checkpoint_blend', 'generalization_program', 'Checkpoint blending', 'local', 'generalization',
      'Interpolate back toward source checkpoints after continuation.', 'Found useful Pareto points.', 'Could not express query-specific expertise.'),
    n('recadam', 'generalization_program', 'RecAdam', 'local', 'generalization',
      'Regularize early updates toward source parameters.', 'Tested as a low-forgetting continuation route.', 'Local technique only.'),
    n('lwf', 'generalization_program', 'Score-retention distillation', 'reject', 'generalization',
      'Preserve source outputs while learning new evidence.', 'No decisive production advantage.', 'Rejected as final architecture.'),
    n('score_distill', 'generalization_program', 'Bidirectional score distillation', 'reject', 'generalization',
      'Preserve the old ranking matrix directly.', 'Useful experiment, no final architectural win.', 'Rejected.'),
    n('margin_mse', 'generalization_program', 'Margin-MSE retention', 'reject', 'generalization',
      'Preserve pairwise ranking margins.', 'No decisive production advantage.', 'Rejected.'),
    n('fisher', 'generalization_program', 'Fisher consolidation', 'reject', 'generalization',
      'Merge parameters weighted by importance.', 'Did not outperform ranking-level organization.', 'Rejected.'),
    n('regmean', 'generalization_program', 'RegMean consolidation', 'reject', 'generalization',
      'Merge representations with closed-form statistics.', 'Did not become the production solution.', 'Rejected.'),
    n('ties', 'generalization_program', 'TIES merging', 'reject', 'generalization',
      'Resolve conflicting task vectors before model merging.', 'Less stable than routing experts at score/rank level.', 'Rejected.'),
    n('adamerging', 'generalization_program', 'AdaMerging', 'reject', 'generalization',
      'Learn model-merging weights automatically.', 'Did not solve bidirectional conditionality robustly.', 'Rejected.'),
    n('lora_considered', 'generalization_program', 'LoRA continuation', 'considered', 'generalization',
      'Explore a low-parameter continuation alternative.', 'Documented as a candidate; not promoted into the frozen production line.', 'Kept as literature/engineering option.', kind='considered'),
    n('dare_considered', 'generalization_program', 'Task-vector merging', 'considered', 'generalization',
      'Explore sparse task-vector merging.', 'Considered lower priority; not a frozen main experiment.', 'Recorded as a considered route.', kind='considered'),
    n('tak_kfac_considered', 'generalization_program', 'Curvature-aware regularization', 'considered', 'generalization',
      'Explore higher-cost curvature-aware retention.', 'Considered advanced backup only.', 'Not promoted into production experiments.', kind='considered'),
    n('posthoc_router', 'generalization_program', 'Post-hoc domain expert routing', 'turn', 'routing',
      'Route queries to domain-specialized models instead of merging everything into one parameter set.', 'Showed expert value depends on query region.', 'Direct ancestor of query applicability.'),
    n('novelty', 'generalization_program', 'Low-similarity novelty branch', 'reject', 'routing',
      'Specialize for reaction-novel queries.', 'Could not survive clean frozen confirmation.', 'Rejected.'),
    n('novelty_replay', 'novelty', 'Novel-reaction replay', 'reject', 'routing',
      'Upweight low-similarity reactions during training.', 'Unstable.', 'Rejected.'),
    n('novelty_expert', 'novelty', 'Novelty expert + similarity route', 'reject', 'routing',
      'Route low-similarity queries to a specialist.', 'No robust general gain.', 'Rejected.'),

    # Broad-era expert evidence program
    n('expert_program', 'broad', 'Expert evidence families', 'keep', 'expert',
      'Identify complementary models that can improve a strong Broad base without replacing it.', 'Produced functional, structural and mechanistic experts.', 'Feeds BiME and BRIDGE.', kind='program'),
    n('enzgfm', 'expert_program', 'EnzGFM native baseline', 'keep', 'expert',
      'Use a strong pretrained enzyme–reaction model.', 'Strong baseline and expert source.', 'Retained.'),
    n('enzgfm_rdkit', 'enzgfm', 'EnzGFM + RDKit', 'local', 'expert',
      'Add explicit reaction chemistry to the foundation model representation.', 'Useful on cleanroom slices.', 'Continued to RDKit+.'),
    n('enzgfm_rdkitplus', 'enzgfm_rdkit', 'EnzGFM with reaction features', 'keep', 'expert',
      'Use richer reaction features and scoped completion.', 'Passed broad cleanroom protocols in selected roles.', 'Retained as expert evidence.'),
    n('equal_block', 'enzgfm_rdkitplus', 'Equal-block feature fusion', 'local', 'expert',
      'Prevent one feature block from dominating by scale/dimension.', 'Useful controlled fusion.', 'Local implementation detail.'),
    n('reaction_center', 'expert_program', 'Reaction-center mechanistic branch', 'turn', 'mechanism',
      'Represent the atoms/bonds that actually change.', 'Standalone mechanism ranking failed; bounded residual succeeded.', 'Key ancestor of bounded corrections.'),
    n('center_v1', 'reaction_center', 'Direct reaction-center fusion', 'reject', 'mechanism',
      'Use reaction-center features as a direct ranking expert.', 'Failed the hard-slice promotion gate.', 'Rejected.'),
    n('center_identity', 'reaction_center', 'Identity-preserving center residual', 'turn', 'mechanism',
      'Make missing/zero correction exactly reproduce Broad.', 'Stable enough to confirm.', 'Moved to bounded V3.'),
    n('center_v3', 'center_identity', 'Bounded reaction-center correction', 'keep', 'mechanism',
      'Cap how far mechanistic evidence can move a strong base order.', 'Passed frozen confirmation.', 'Direct BRIDGE design ancestor.'),
    n('top2000', 'expert_program', 'Shortlist pair reranking', 'turn', 'expert',
      'Spend expensive pair modeling only on the broad shortlist.', 'Localized computation and reduced damage to tail order.', 'Led to difficulty-aware and anchored reranking.'),
    n('pair_reranker', 'top2000', 'Pairwise shortlist correction', 'local', 'expert',
      'Learn pairwise corrections inside the shortlist.', 'Useful development signal.', 'Kept as a local mechanism.'),
    n('bounded_top2000', 'top2000', 'Bounded shortlist correction', 'local', 'expert',
      'Limit reranker authority over Broad.', 'Passed a fold-specific confirmation.', 'Strengthened the bounded-correction principle.'),
    n('difficulty_router', 'top2000', 'Difficulty-aware shortlist routing', 'keep', 'routing',
      'Run local reranking only on queries that need it.', 'Confirmed.', 'Kept as a routing precursor.'),
    n('center_gate', 'top2000', 'Reaction-center shortlist gate', 'reject', 'routing',
      'Use center evidence to decide when to activate reranking.', 'Comprehensive integration was rejected.', 'Specific gate dropped; routing idea survived.'),
    n('functional_proto', 'expert_program', 'Functional-prototype residual', 'reject', 'expert',
      'Correct Broad from train-only function prototypes.', 'Failed the formal selector.', 'Rejected.'),
    n('clipzyme', 'expert_program', 'CLIPZyme structural branch', 'turn', 'structure',
      'Add structure-aware evidence from a separate model family.', 'Useful only when native inputs/support were respected.', 'Became an availability-aware structural expert.'),
    n('clip_native', 'clipzyme', 'Native CLIPZyme baseline', 'keep', 'structure',
      'Evaluate CLIPZyme under its own native semantics.', 'Established a fair structural baseline.', 'Retained as expert ancestry.'),
    n('clip_encoder_sub', 'clipzyme', 'CLIPZyme encoder substitution', 'reject', 'structure',
      'Replace the original encoder to fit local assets.', 'Changed model semantics; reverted.', 'Rejected.'),
    n('clip_support', 'clipzyme', 'Structure-support audits', 'keep', 'structure',
      'Make structure-expert availability explicit and auditable.', 'Identified which candidates could be scored faithfully.', 'Retained as availability contract.'),
    n('clip_fallback', 'clipzyme', 'Directed CLIPZyme fallback', 'keep', 'structure',
      'Use structure evidence only when supported and restore baseline otherwise.', 'Passed fallback contract tests.', 'Direct predecessor of missing-neutral expert semantics.'),
    n('reactzyme', 'expert_program', 'ReactZyme transfer branch', 'turn', 'structure',
      'Test another structural/native molecule-bag model family.', 'Native adapter reproduced author semantics, retention failed.', 'Useful negative evidence for universal transfer.'),
    n('reactzyme_bag', 'reactzyme', 'Native molecule-bag adapter', 'local', 'structure',
      'Match the author input representation exactly.', 'Confirmed adapter behavior.', 'Kept for reproducible comparison.'),
    n('reactzyme_retention', 'reactzyme', 'ReactZyme retention policy', 'reject', 'structure',
      'Decide whether ReactZyme should enter the production expert set.', 'Retention gate rejected it.', 'Rejected.'),

    # Evaluation stress program
    n('stress_program', 'broad', 'External & temporal stress tests', 'keep', 'evaluation',
      'Prevent method selection from being driven by one internal split.', 'Several routes failed only when moved to external/fresh support.', 'Kept as selection discipline.', kind='program'),
    n('cleanroom_nested', 'stress_program', 'Leakage-safe nested cleanroom selection', 'keep', 'evaluation',
      'Keep model selection separate from frozen/external confirmation.', 'Became mandatory selection discipline.', 'Retained.'),
    n('pure_cage_baseline', 'stress_program', 'Pure EnzymeCAGE same-support baseline', 'keep', 'evaluation',
      'Reconstruct a fair CAGE baseline on its native support.', 'Established auditable apples-to-apples comparison.', 'Retained as baseline evidence.'),
    n('enzyme405', 'stress_program', 'Enzyme-405 same-support comparison', 'keep', 'evaluation',
      'Compare against EnzymeCAGE on its supported evaluation domain.', 'Provided fair external comparison.', 'Retained as benchmark evidence.'),
    n('orphan335', 'stress_program', 'Orphan-335 retrieval stress test', 'keep', 'evaluation',
      'Test reaction-novel retrieval.', 'Provided an external broad-retrieval challenge.', 'Retained as stress evidence.'),
    n('tiger', 'stress_program', 'TIGER reaction-novel baseline', 'local', 'evaluation',
      'Include a reproducible external reaction-novel baseline.', 'Useful for fair comparison.', 'Benchmark-only.'),
    n('rhea_transfer', 'stress_program', 'Fresh temporal transfer test', 'reject', 'evaluation',
      'Test fixed models on a fresher Rhea snapshot.', 'Transfer failures exposed support/alignment limits.', 'Used to constrain claims, not as a production route.'),
    n('tps_marts_symmetry', 'stress_program', 'TPS MARTS R2E symmetry confirmation', 'keep', 'evaluation',
      'Check whether the TPS route behaved coherently in the opposite retrieval direction.', 'Passed its dedicated confirmation.', 'Retained as capability evidence.'),
    n('temporal', 'stress_program', 'Strict temporal benchmark', 'keep', 'evaluation',
      'Measure performance on future/held-out evidence rather than only random folds.', 'Became part of final model evaluation discipline.', 'Retained.'),

    # Fusion / routing program to BiME
    n('fusion_program', 'broad', 'Rank fusion & expert routing', 'turn', 'fusion',
      'Combine complementary models without letting arbitrary scales or weak experts destroy the base.', 'Fixed fusion repeatedly failed; learned/anchored routing worked better.', 'Direct parent of BiME-Rank.', kind='program', main=True),
    n('raw_add', 'fusion_program', 'Raw score addition', 'reject', 'fusion',
      'Use the simplest possible ensemble.', 'Score scales were incompatible.', 'Rejected.'),
    n('percentile', 'fusion_program', 'Tied-rank percentile fusion', 'local', 'fusion',
      'Normalize each model within query before combining.', 'Useful in selected routes.', 'Kept locally.'),
    n('rrf', 'fusion_program', 'Reciprocal Rank Fusion', 'local', 'fusion',
      'Fuse relative order instead of raw score.', 'Stable for selected E2R Top-10 routes.', 'Retained locally.'),
    n('e2r_top10_rrf', 'rrf', 'Dual-neural E2R rank fusion', 'local', 'fusion',
      'Combine two complementary E2R neural routes without raw-score calibration.', 'Survived repeated confirmation for Top-10.', 'Retained as a budget-specific route.'),
    n('three_source', 'fusion_program', 'Fixed three-source fusion', 'turn', 'fusion',
      'Exploit unique hits from Pfam, kernel and neural experts.', 'Development improved; frozen performance fell.', 'Proved complementarity does not imply global fixed weights.'),
    n('early_lambdarank', 'fusion_program', 'Early TPS LambdaRank candidate stacking', 'reject', 'fusion',
      'Learn expert fusion rather than set weights manually.', 'Too little/unstable data in the early TPS setting.', 'Rejected then later revisited on broad clean data.'),
    n('portfolio', 'fusion_program', 'Retrieval expert portfolio selection', 'turn', 'fusion',
      'Select only experts that add complementary clean evidence.', 'Produced a manageable expert set.', 'Led to R2E LambdaRank.', main=True),
    n('candidate_union', 'portfolio', 'Expert candidate union', 'keep', 'fusion',
      'Let independent experts contribute candidates before learning the final order.', 'Improved support without requiring one universal retriever.', 'Retained in BiME.'),
    n('r2e_lambdarank', 'portfolio', 'R2E LambdaRank stack', 'keep', 'fusion',
      'Learn from raw scores, normalized scores, ranks, reciprocal ranks, agreement and novelty.', 'Passed frozen confirmation.', 'Main direct parent of BiME-Rank.', main=True),
    n('r2e_similarity_router', 'r2e_lambdarank', 'R2E similarity router', 'keep', 'routing',
      'Use query novelty/similarity to select safe routes.', 'Confirmed deterministic routing.', 'Retained.'),
    n('joint_reliability_gate', 'r2e_lambdarank', 'Joint reliability gate', 'local', 'routing',
      'Prevent routed experts from degrading metrics when evidence is weak.', 'Improved safety constraints.', 'Fed expert admission logic.'),
    n('bime', 'r2e_lambdarank', 'BiME-Rank', 'keep', 'milestone',
      'Institutionalize multi-expert retrieval with admission, fallbacks, context and cost-aware execution.',
      'Strong multi-expert predecessor, but expert value was still mostly admitted globally/task-wise.',
      'Direct predecessor of BRIDGE.', kind='milestone', main=True),

    # BiME subtrees
    n('e2r_branch', 'bime', 'E2R expert-fusion branch', 'turn', 'fusion',
      'Transfer R2E multi-expert success to E2R.', 'Unrestricted fusion damaged a very strong EnzGFM base.', 'Forced explicit base protection.'),
    n('e2r_four', 'e2r_branch', 'Four-expert E2R LambdaRank', 'reject', 'fusion',
      'Let all experts freely rerank E2R.', 'Rejected after head-ranking degradation.', 'Rejected.'),
    n('e2r_rescue', 'e2r_branch', 'Baseline-anchored E2R rescue', 'turn', 'fusion',
      'Protect the strong baseline and let experts rescue only selected items.', 'Safer than unrestricted fusion.', 'Led to Anchored LambdaMART.'),
    n('e2r_anchor', 'e2r_rescue', 'Anchored E2R learning-to-rank', 'keep', 'fusion',
      'Protect Top-1 and rerank only a limited prefix/union.', 'Passed confirmation.', 'Direct ancestor of BRIDGE base-order protection.'),
    n('admission', 'bime', 'Formal expert admission', 'keep', 'routing',
      'Require internal clean gains, external veto-only confirmation and exact fallback when unavailable.', 'Made expert inclusion auditable.', 'Retained conceptually.'),
    n('bime_clip', 'admission', 'CLIPZyme structural expert', 'keep', 'structure',
      'Promote the support-aware structural route into BiME.', 'Passed admission.', 'Retained.'),
    n('seed_context', 'admission', 'Seed context expert', 'keep', 'context',
      'Use known-positive context as a conditional second-stage signal.', 'Conditionally admitted.', 'Retained.'),
    n('multi_seed_context', 'seed_context', 'Multi-seed context', 'keep', 'context',
      'Allow several known positives to define context.', 'Validated in BiME.', 'Retained as conditional context.'),
    n('homology_context', 'admission', 'Homology context expert', 'reject', 'context',
      'Promote homology into a common expert.', 'Failed external retention.', 'Rejected.'),
    n('reciprocal_expert', 'admission', 'Reciprocal consistency expert', 'reject', 'context',
      'Turn cycle agreement into a formal expert.', 'Failed external retention.', 'Rejected.'),
    n('generic_cage_expert', 'admission', 'Generic EnzymeCAGE expert', 'turn', 'structure',
      'Return CAGE as a universal structural expert.', 'Internal OOF ranking degraded.', 'Critical evidence that structural expertise is conditional.'),
    n('cost_hierarchy', 'bime', 'Cost-aware hierarchical execution', 'keep', 'routing',
      'Avoid running expensive experts over the full candidate universe.', 'Cheap experts search broadly; expensive experts run on shortlists.', 'Retained in final execution philosophy.'),
    n('strong_base_policy', 'bime', 'Strong-baseline absorption policy', 'keep', 'routing',
      'Prevent new experts from displacing a clearly stronger incumbent without evidence.', 'Formalized conservative integration.', 'Direct BRIDGE precursor.'),

    # FIBRE
    n('fibre', 'bime', 'FIBRE unified-model detour', 'historical', 'fibre',
      'Test the strongest alternative hypothesis: replace modular expert assembly with one unified relational/interaction geometry.',
      'Produced a coherent research line but never replaced Broad as the universal ordering core.',
      'Archived; several design conclusions survived into BRIDGE.', kind='milestone'),
    n('bio_relation', 'fibre', 'Biological relation stratification', 'historical', 'fibre',
      'Represent richer biological correspondence than binary positive/negative pairs.', 'Established FIBRE relation semantics.', 'Historical foundation.'),
    n('mechanistic_strata', 'bio_relation', 'Mechanistic relation strata', 'historical', 'fibre',
      'Separate different biochemical relation types.', 'Integrated into FIBRE observations.', 'Historical.'),
    n('partial_relation', 'bio_relation', 'Partial biological relation', 'historical', 'fibre',
      'Allow incomplete but meaningful correspondence evidence.', 'Implemented in the FIBRE observation model.', 'Historical.'),
    n('context_domain', 'fibre', 'Context-restricted FIBRE domain', 'historical', 'fibre',
      'Make each local relation model valid only in an explicit domain.', 'Improved semantic honesty.', 'Conceptually survived as applicability.'),
    n('tensor_field', 'fibre', 'Tensor-product atlas field', 'historical', 'fibre',
      'Model enzyme × reaction interactions explicitly.', 'Implemented and evaluated.', 'Historical.'),
    n('interaction_atlas', 'tensor_field', 'Interaction Atlas', 'historical', 'fibre',
      'Interpret heterogeneous experts as local charts of one interaction space.', 'Became a full FIBRE formulation.', 'Historical.'),
    n('atlas_gluing', 'interaction_atlas', 'Atlas gluing loss', 'reject', 'fibre',
      'Force overlapping charts to agree.', 'Cross-expert consistency assumptions were too strong.', 'Removed.'),
    n('catalytic_kernel', 'fibre', 'Catalytic kernel formulation', 'historical', 'fibre',
      'Ground the interaction geometry in catalytic interpretation.', 'Improved theory, not empirical ranking dominance.', 'Historical.'),
    n('conditional_kinetics', 'catalytic_kernel', 'Conditional catalytic kinetics', 'historical', 'fibre',
      'Interpret query conditioning through catalytic modes.', 'Used to refine theory.', 'Historical.'),
    n('mode_uncertainty', 'conditional_kinetics', 'Hierarchical mode uncertainty', 'historical', 'fibre',
      'Represent uncertainty over latent catalytic modes.', 'Theoretical refinement.', 'Historical.'),
    n('conditional_modes', 'fibre', 'FIBRE conditional modes', 'historical', 'fibre',
      'Use one general mode plus query-conditioned local modes.', 'Became the largest FIBRE model-selection subtree.', 'Historical selection hub.'),
    n('consistency_penalty', 'conditional_modes', 'Cross-expert consistency penalty', 'reject', 'fibre',
      'Encourage experts to agree on overlapping evidence.', 'Deleting the penalty simplified the model without losing performance.', 'Removed.'),
    n('symmetric_potential', 'conditional_modes', 'Fully symmetric joint potential', 'reject', 'fibre',
      'Use one symmetric pair score for R2E and E2R.', 'Lost real direction-specific information.', 'Rejected.'),
    n('geomean_gate', 'conditional_modes', 'Geometric-mean two-sided gates', 'reject', 'fibre',
      'Combine reaction- and enzyme-side gates symmetrically.', 'Unstable across directions.', 'Rejected.'),
    n('symmetric_linear', 'conditional_modes', 'Symmetric linear expert mixture', 'reject', 'fibre',
      'Simplify joint conditional mixing.', 'Did not resolve directional degradation.', 'Rejected.'),
    n('gibbs', 'conditional_modes', 'Log-partition expert aggregation', 'reject', 'fibre',
      'Use an energy-style soft aggregation.', 'No stable gain.', 'Rejected.'),
    n('kl_bary', 'conditional_modes', 'Entropy-weighted KL barycenter', 'reject', 'fibre',
      'Fuse directional expert distributions using uncertainty.', 'No stable gain.', 'Rejected.'),
    n('molecular_comp', 'conditional_modes', 'Molecular joint-potential compensation', 'reject', 'fibre',
      'Compensate directional mismatch with extra molecular potential.', 'Insufficient.', 'Rejected.'),
    n('variance_fallback', 'conditional_modes', 'Expert-disagreement variance fallback', 'reject', 'fibre',
      'Automatically shrink corrections when experts disagree.', 'R2E degraded.', 'Rejected.'),
    n('normalized_mix', 'conditional_modes', 'Normalized conditional expert mixture', 'reject', 'fibre',
      'Normalize incomparable expert score scales before mixing.', 'R2E degraded strongly.', 'Rejected.'),
    n('dim_consistency', 'conditional_modes', 'Dimension-scaled consistency', 'reject', 'fibre',
      'Choose consistency strength from representation dimension.', 'No advantage over deleting consistency.', 'Rejected.'),
    n('linear_expectation', 'conditional_modes', 'Directional linear conditional expectation', 'local', 'fibre',
      'Preserve direction-specific conditional information.', 'Most stable FIBRE conditional mode.', 'Historical local winner.'),
    n('logmeanexp', 'conditional_modes', 'Log-Mean-Exp aggregation', 'reject', 'fibre',
      'Use nonlinear soft aggregation of modes.', 'Development acceptable, frozen evaluation failed.', 'Rejected.'),
    n('second_order', 'conditional_modes', 'Second-order variance correction', 'reject', 'fibre',
      'Add expert-disagreement curvature to the score.', 'Failed development R2E.', 'Rejected.'),
    n('rc_posterior', 'conditional_modes', 'Reaction-center mode posterior', 'reject', 'fibre',
      'Update R2E mode priors using reaction-center evidence without contaminating E2R.', 'Development improved, frozen R2E degraded.', 'Rejected.'),
    n('scientific_evidence', 'fibre', 'Anchored scientific-evidence layer', 'turn', 'fibre',
      'Move real structure/mechanism/context evidence outside the latent geometry and anchor it on a core score.', 'This formulation was substantially more stable.', 'Major surviving FIBRE idea.'),
    n('structure_evidence', 'scientific_evidence', 'Structure scientific evidence', 'keep', 'fibre',
      'Add structure evidence only after admission and calibration.', 'Passed evidence admission.', 'Survived as structural expert semantics.'),
    n('known_context', 'scientific_evidence', 'Known-positive context evidence', 'keep', 'fibre',
      'Add seed context as independent evidence.', 'Stable conditional capability.', 'Survived.'),
    n('rc_evidence', 'scientific_evidence', 'Reaction-center scientific evidence', 'local', 'fibre',
      'Use mechanism evidence as an explicit channel.', 'Informative pair evidence but ranking admission was weaker.', 'Retained mostly as evidence.'),
    n('evidence_admission', 'scientific_evidence', 'Evidence admission and calibration', 'turn', 'fibre',
      'Require early-ranking gain and frozen confirmation before evidence can rerank.', 'Tightened expert permission semantics.', 'Survived into BRIDGE gating.'),
    n('hcm', 'fibre', 'Heterogeneous Conditional Modes', 'turn', 'fibre',
      'Put EnzGFM, reaction center, CLIPZyme and seed context in one availability-aware graph.', 'Unified execution worked; universal FIBRE core still did not dominate.', 'Modularity survived.'),
    n('query_mix', 'hcm', 'Query-adaptive expert mixture', 'turn', 'fibre',
      'Learn expert weights per query.', 'The safe version required freezing the core.', 'Led toward explicit applicability.'),
    n('query_mix_e2e', 'query_mix', 'End-to-end bidirectional gate', 'reject', 'fibre',
      'Learn query gates jointly with the core.', 'Damaged R2E.', 'Rejected.'),
    n('query_mix_e2r', 'query_mix', 'E2R-only gate', 'reject', 'fibre',
      'Restrict adaptive mixing to the safer direction.', 'Shared training still hurt R2E.', 'Rejected.'),
    n('query_mix_posthoc', 'query_mix', 'Frozen-core post-hoc gate', 'turn', 'fibre',
      'Freeze the strong core and learn only a light query gate.', 'Preserved R2E exactly; E2R gain was insufficient for promotion.', 'Validated the safe gating pattern.'),
    n('eram', 'fibre', 'ERAM relational core', 'turn', 'fibre',
      'Replace hand-designed FIBRE geometry with a modern broad relational learner.', 'Implemented, trained and served.', 'Still failed to displace Broad.'),
    n('unimol', 'eram', 'UniMol feature preparation', 'historical', 'fibre',
      'Provide structured molecular features to ERAM.', 'Implemented.', 'Historical.'),
    n('relational_main', 'eram', 'Relational main model', 'reject', 'fibre',
      'Let the relational core become the main ranking model.', 'Strict double-cold/temporal evaluation did not justify replacing Broad.', 'Rejected as universal core.'),
    n('temporal_relational', 'relational_main', 'Strict temporal + double-cold relational evaluation', 'keep', 'evaluation',
      'Test the replacement under hard generalization protocols.', 'Supported the decision to keep Broad as base.', 'Retained as evidence.'),
    n('plugins', 'fibre', 'Pluggable expert adapters', 'turn', 'fibre',
      'Allow new evidence sources without retraining one universal core.', 'Implemented successfully.', 'Directly survived into BRIDGE modularity.'),
    n('context_plugin', 'plugins', 'Frozen context plugin', 'turn', 'fibre',
      'Add context as a frozen external module.', 'Validated plug-in execution.', 'Survived.'),
    n('open_fallback', 'plugins', 'Open-world fallback', 'keep', 'fibre',
      'Ensure the system remains valid when plugins are unavailable.', 'Preserved broad fallback.', 'Survived as missing-neutral behavior.'),

    # Return from FIBRE to Broad and final routing
    n('return_broad', 'bime', 'Return to Broad as ordering core', 'turn', 'final',
      'Repeated unified-core experiments failed to beat the stable broad base.', 'The architecture was reframed around ranking authority rather than one representation.', 'Starts the final BRIDGE line.', kind='milestone', main=True),
    n('pair_evidence', 'return_broad', 'Experts as pair evidence', 'keep', 'final',
      'Treat experts as query–candidate evidence rather than replacement representations.', 'Created a clean correction interface.', 'Retained.'),
    n('rebind_broad', 'return_broad', 'Rebind expert evidence to Broad Core', 'keep', 'final',
      'Restore the strongest global ordering authority.', 'Broad became the explicit base again.', 'Retained.'),
    n('broad_calibration', 'rebind_broad', 'Calibrate Broad before evidence fusion', 'keep', 'final',
      'Make base scores stable before optional corrections are applied.', 'Reduced arbitrary evidence-scale effects.', 'Retained.'),
    n('score_evidence', 'return_broad', 'Directional score evidence', 'keep', 'final',
      'Allow the same expert to have different ranking rights in R2E vs E2R.', 'EnzGFM evidence showed direction-specific admission behavior.', 'Retained.'),
    n('expert_types', 'return_broad', 'Expert-type hierarchy', 'keep', 'final',
      'Organize foundation/function, structure, mechanism, context and family specialists.', 'Made responsibilities explicit.', 'Retained.'),
    n('dynamic_v4', 'return_broad', 'Query-conditioned expert routing', 'turn', 'final',
      'Make expert use depend on query properties.', 'Established query-conditioned expert weighting.', 'Refined into explicit applicability.', main=True),
    n('dynamic_v6', 'dynamic_v4', 'Expert permission levels', 'keep', 'final',
      'Separate experts that may rerank, experts that only report evidence, and experts that must stay silent.', 'Produced a safer permission model.', 'Direct BRIDGE ancestor.', main=True),
    n('query_applicability', 'dynamic_v6', 'Query-level expert applicability', 'keep', 'final',
      'Ask “is this expert useful for this query and direction?” rather than “is this expert globally admitted?”',
      'Explained generic-expert failures and specialist successes consistently.', 'Core BRIDGE principle.', kind='milestone', main=True),
    n('cage_family', 'query_applicability', 'CAGE family-response branch', 'turn', 'structure',
      'Re-test CAGE where its structural assumptions are locally coherent.', 'Family-tuned CAGE improved several domains despite generic CAGE failure.', 'Became gated family specialists.'),
    n('p450_cage', 'cage_family', 'P450 CAGE specialist', 'keep', 'structure',
      'Test local structural expertise in P450.', 'Clear local improvement.', 'Retained under family gate.'),
    n('phosphatase_cage', 'cage_family', 'Phosphatase CAGE specialist', 'keep', 'structure',
      'Test local structural expertise in phosphatases.', 'Clear local improvement.', 'Retained under family gate.'),
    n('terpene_cage', 'cage_family', 'Terpene CAGE specialist', 'keep', 'structure',
      'Revisit CAGE in the original chemistry domain.', 'Local improvement.', 'Retained under family gate.'),
    n('tps_correction', 'query_applicability', 'TPS specialist correction', 'keep', 'mechanism',
      'Reuse the earliest TPS-specific model knowledge without narrowing the whole system.', 'Activated sparsely on TPS-applicable queries.', 'Retained as a gated specialist.'),
    n('integrated_specialists', 'query_applicability', 'Integrated gated domain specialists', 'keep', 'final',
      'Combine query applicability, family specialists and the Broad base under one permission contract.', 'Improved local domains without reducing broad coverage.', 'Immediate predecessor of BRIDGE.', main=True),
    n('layered_cage_eval', 'integrated_specialists', 'Layered EnzymeCAGE full-suite comparison', 'keep', 'evaluation',
      'Compare original CAGE, Broad→generic CAGE and the full gated system on the same layered suite.', 'Showed candidate coverage and expert scoreability are distinct constraints.', 'Supports the final narrative.'),
    n('bridge', 'integrated_specialists', 'BRIDGE', 'keep', 'final',
      'Keep Broad as the stable universal order while experts earn query- and direction-specific bounded correction rights.',
      'Combines broad coverage, expert modularity, missing-neutral semantics, specialist locality and protected base ranking.',
      'Current method.', kind='milestone', main=True),
]


CROSSLINKS = [
    dict(source='semantic_scope', target='user_semantic_routing', label='scope switching became a user interaction problem'),
    dict(source='bridge', target='compass', label='current retrieval backend served through COMPASS'),
    dict(source='wetlab_feedback', target='fewshot', label='confirmed positives can seed later retrieval'),
    dict(source='generalization_program', target='fusion_program', label='continuation trade-offs forced expert decomposition'),
    dict(source='expert_program', target='fusion_program', label='heterogeneous evidence required explicit routing'),
    dict(source='reaction_transfer', target='broad', label='candidate evidence survives'),
    dict(source='marts_candidates', target='marts_adapt', label='external domain data'),
    dict(source='uniprot_quota', target='broad', label='controlled expansion'),
    dict(source='taxonomy', target='bridge', label='candidate-universe constraint survives'),
    dict(source='horizyn_residual', target='center_identity', label='residual principle'),
    dict(source='rescue_slots', target='e2r_rescue', label='protect base, allow rescue'),
    dict(source='rescue_slots', target='bridge', label='bounded correction ancestry'),
    dict(source='applicability_proxy', target='query_applicability', label='applicability, not activity'),
    dict(source='mondrian', target='query_applicability', label='conditional support idea'),
    dict(source='cycle', target='reciprocal_expert', label='diagnostic promoted then rejected'),
    dict(source='dual_kernel_marts', target='bime', label='budget-specific expert evidence'),
    dict(source='posthoc_router', target='dynamic_v4', label='query-conditioned routing'),
    dict(source='early_lambdarank', target='r2e_lambdarank', label='revisited with broad clean data'),
    dict(source='enzgfm_rdkitplus', target='r2e_lambdarank', label='foundation expert'),
    dict(source='center_v3', target='r2e_lambdarank', label='mechanistic expert'),
    dict(source='center_v3', target='bridge', label='bounded correction'),
    dict(source='clip_fallback', target='bime_clip', label='availability-aware structure'),
    dict(source='reactzyme_retention', target='admission', label='negative admission evidence'),
    dict(source='e2r_anchor', target='bridge', label='base-order protection'),
    dict(source='cost_hierarchy', target='bridge', label='hierarchical execution'),
    dict(source='generic_cage_expert', target='cage_family', label='generic failure motivates family scope'),
    dict(source='tps_foundation', target='tps_correction', label='TPS specialist ancestry'),
    dict(source='tps_xattn', target='tps_correction', label='active-site specialist lessons'),
    dict(source='context_domain', target='query_applicability', label='local domain idea survives'),
    dict(source='scientific_evidence', target='pair_evidence', label='explicit evidence over latent geometry'),
    dict(source='evidence_admission', target='dynamic_v6', label='permission by evidence'),
    dict(source='query_mix_posthoc', target='dynamic_v4', label='freeze core, adapt gate'),
    dict(source='relational_main', target='rebind_broad', label='replacement failed → restore Broad'),
    dict(source='plugins', target='expert_types', label='pluggable expert architecture'),
    dict(source='open_fallback', target='bridge', label='missing-neutral fallback'),
    dict(source='known_context', target='seed_context', label='context lineage'),
    dict(source='structure_evidence', target='cage_family', label='admitted structure evidence'),
    dict(source='strong_base_policy', target='rebind_broad', label='protect incumbent'),
    dict(source='frozen_tower', target='score_evidence', label='direction-specific behavior'),
]

FAMILY_LABELS = {
    'root': 'EnzymeCAGE / problem framing',
    'candidate': 'Candidate universe',
    'representation': 'Representation & retrieval',
    'training': 'Training objectives',
    'mechanism': 'Mechanistic / TPS specialization',
    'structure': 'Structural evidence',
    'uncertainty': 'Reliability & applicability',
    'graph': 'Graph / non-parametric',
    'generalization': 'Generalization / retention',
    'routing': 'Routing / permissions',
    'expert': 'Expert evidence',
    'evaluation': 'External / temporal evaluation',
    'fusion': 'Fusion / learning-to-rank',
    'context': 'Context evidence',
    'fibre': 'FIBRE detour',
    'final': 'Return to Broad / BRIDGE',
    'milestone': 'Milestones',
}
